### ISSUE TITLE
missing changes

### ISSUE THREAD

**Issue by thorowitz** [manubot/rootstock#360]
I merged changes into the master branch 6 days ago. However, we noticed that the edits had not been made to the file. That is, someone created a branch, made edits to the file, I approved the changes and merged the changes into the main document, then deleted the branch. There were no errors or indications that anything went wrong, yet the changes are not there in the main file. What could have happened here?

**Comment by agitter** [comment]
Are the changes missing from the content files on the master branch or from the generated manuscript files on the gh-pages branch?  If they are missing from master, is it possible that parallel branches had conflicts or made edits to the same parts of the content.  Depending on the merge order and how any conflicts were resolved, that could revert some of the edits.

If the changes are present on the master branch and missing from the gh-pages manuscript, it is possible there was a build error and the output files were not generated for one or more master branch commits.

Inspecting the GitHub Insights -> Network (e.g. https://github.com/manubot/rootstock/network) can sometimes help reveal why a merge or branch didn't work as expected.  That type of git history visualization is also available in local git clients if you don't have it available in GitHub.

Opening the content file in GitHub and using the Blame button can also help inspect the file's history and which commits last edited different parts of the file.

**Comment by thorowitz** [comment]
Oddly, the master branch and the output files do not match. The edits I was looking for are present in the manuscript.pdf, but not in the master branch, vice versa for other edits.
The repository is private, so I can't see the history visualization, and I don't see it in GitHub Desktop.
The edit that I'm looking for does not show up in the blame file.

**Comment by agitter** [comment]
I'm not sure how the manuscript.pdf could be out of sync with the content on the master branch.  If this pertains to the private repository you gave me access to previously and I still have access, you could provide more details there.  If you create an issue in the private repo and tag me, let me know which specific content is on the master branch but not the output pdf.  I can investigate further.

**Comment by thorowitz** [comment]
Yes, it's in that repo, and you should still have access. I opened an issue and tagged you. The changes are now gone from the output branch!

**Comment by agitter** [comment]
I added more details in the private repository.  The summary for anyone facing a similar issue is that the GitHub Actions build for a merge commit on the master branch was re-run.  This may have caused that commit's content to overwrite content from a later commit, temporarily making output/gh-pages out of sync with master.

The master branch changes were reverted by a merge commit to master.

I don't think we need to modify the Manubot deploy step to behave differently if it is being run for a second time.  As long as the content on master is correct, the output and gh-pages branches will re-sync with the next build.
